export const products = [
    {
        id:1,
        name: "Acrylic Paint Set (12 Colors)",
        price: 25.99,
        type: "Paint and Brushes",
        description: "This set includes 12 high-pigment acrylic paints that deliver rich, vibrant colors. Each tube is designed for easy application on a variety of surfaces like canvas, wood, and paper. The quick-drying formula makes it perfect for layering and blending, catering to both beginners and experienced artists.",
        image: "$lib/imgs/acrylicpaintset.jpg",
    },
    {
        id:2,
        name: "Watercolor Pan Set (24 Colors)",
        price: 19.99,
        type: "Paint and Brushes",
        description: "A compact and portable watercolor set with 24 vibrant pans. This set includes a water brush pen and mixing tray, making it ideal for artists on the go. The colors are easy to activate with water and offer excellent transparency for creating delicate, layered effects.",
        image: "$lib/imgs/watercolor24.jpg",
    },
    {
        id:3,
        name: "Round Paintbrush Set (6 Brushes)",
        price: 12.99,
        type: "Paint and Brushes",
        description: "This versatile set includes six round brushes of varying sizes, made with durable synthetic bristles for precision and smooth strokes. Perfect for fine details or broad washes in watercolor, acrylic, or gouache projects. Comes with ergonomic wooden handles for comfort during long sessions.",
        image: "$lib/imgs/roundbrush6.jpg",
    },
    {
        id:4,
        name: "Graphite Pencil Set (12 Pencils)",
        price: 14.59,
        type: "Sketching and Drawing",
        description: "A comprehensive set of 12 high-quality graphite pencils ranging from 6H to 8B. The pencils are designed for sketching, shading, and detailed drawing, with break-resistant cores for durability. Ideal for creating subtle gradients and bold contrasts in your work.",
        image: "$lib/imgs/grphitepencilset12.jpg",
    },
    {
        id:5,
        name: "Charcoal Drawing Kit",
        price: 17.49,
        type: "Sketching and Drawing",
        description: "This kit includes 2 charcoal pencils, 3 charcoal sticks, a sharpener, and a kneaded eraser for creating dramatic, textured drawings. The soft, rich charcoal is perfect for adding depth and boldness to sketches. An excellent choice for figure drawing or life studies.",
        image: "$lib/imgs/charcoaldrawwingkit.jpg",
    },
    {
        id:6,
        name: "Colored Pencil Set (36 Colors)",
        price: 24.99,
        type: "Sketching and Drawing",
        description: "A set of 36 vibrant, blendable colored pencils crafted for smooth application and detailed work. Each pencil features a break-resistant core and high pigment concentration, ensuring consistent color with minimal sharpening. Great for layering, shading, and intricate designs.",
        image: "$lib/imgs/coloredpencilset.jpg",
    },
    {
        id:7,
        name: 'Mixed Media Sketchbook (9"x12")',
        price: 15.99,
        type: "Paper and Canvas",
        description: "A spiral-bound sketchbook featuring 60 heavyweight sheets, this pad is perfect for both dry and wet media, including pencils, markers, and light washes of paint. The acid-free paper prevents fading, ensuring your artwork stays vibrant over time.",
        image: "$lib/imgs/mixedmediasketchbook.jpg",
    },
    {
        id:8,
        name: 'Stretched Canvas (3-Pack, 11"x14")',
        price: 18.99,
        type: "Paper and Canvas",
        description: "These premium pre-stretched and primed canvases are ready to use with acrylic or oil paints. Each canvas is stretched over a sturdy wooden frame and primed with acid-free gesso, offering a smooth and consistent surface for painting.",
        image: "$lib/imgs/stretchedcanvas3pack.jpg",
    },
    {
        id:9,
        name: 'Watercolor Paper Pad (9"x12")',
        price: 22.99,
        type: "Paper and Canvas",
        description: "This pad includes 30 sheets of cold-pressed, acid-free watercolor paper, known for its excellent texture and durability. The 140lb paper absorbs water without warping, making it perfect for washes, layering, and detailed work.",
        image: "$lib/imgs/watercolorpaperpad.jpg",
    },
]